
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecodealliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.cargo-vet]
audit-as-crates-io = false

[[exemptions.addr2line]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "0.7.18"
criteria = "safe-to-deploy"

[[exemptions.ansi_term]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.backtrace-ext]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.camino]]
version = "1.0.9"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.23"
criteria = "safe-to-deploy"

[[exemptions.console]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "4.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.educe]]
version = "0.4.20"
criteria = "safe-to-deploy"

[[exemptions.encode_unicode]]
version = "0.3.6"
criteria = "safe-to-deploy"

[[exemptions.enum-ordinalize]]
version = "3.1.12"
criteria = "safe-to-deploy"

[[exemptions.filetime]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.6"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.26.1"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.13"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.7.1"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.19"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.23.0"
criteria = "safe-to-deploy"

[[exemptions.indicatif]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.insta]]
version = "1.16.0"
criteria = "safe-to-run"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.57"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.3"
criteria = "safe-to-deploy"
suggest = false

[[exemptions.libz-sys]]
version = "1.1.15"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.miette]]
version = "5.9.0"
criteria = "safe-to-deploy"

[[exemptions.miette-derive]]
version = "5.9.0"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.16"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.1"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.28.4"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.os_str_bytes]]
version = "6.1.0"
criteria = "safe-to-deploy"

[[exemptions.owo-colors]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.pathdiff]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.2.0"
criteria = "safe-to-deploy"
suggest = false

[[exemptions.redox_syscall]]
version = "0.2.13"
criteria = "safe-to-deploy"
suggest = false

[[exemptions.redox_users]]
version = "0.5.0"
criteria = "safe-to-deploy"
suggest = false

[[exemptions.regex]]
version = "1.5.6"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.26"
criteria = "safe-to-deploy"

[[exemptions.reqwest]]
version = "0.11.11"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.16.20"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.20.6"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.smawk]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.supports-color]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.supports-hyperlinks]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.supports-unicode]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.tar]]
version = "0.4.38"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.termcolor]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.terminal_size]]
version = "0.1.17"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.23.4"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.35"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.27"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.11"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-linebreak]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.80"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.80"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.30"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.80"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.80"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.57"
criteria = "safe-to-deploy"

[[exemptions.webpki]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.22.3"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winreg]]
version = "0.10.1"
criteria = "safe-to-deploy"
